import type { Metadata } from "next";
import { Sidebar } from "../common/Sidebar";
import Header from "../common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen">
      <div className="bg-green-bg sticky top-0 flex h-screen w-[250px] flex-col px-4 pt-[22px]">
        <Sidebar />{" "}
      </div>
      <main className="bg-white-bg flex-1 overflow-y-auto rounded-tl-3xl rounded-bl-3xl px-7">
        <Header />
        {children}
      </main>
    </div>
  );
}
