import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import MainLayout from "@/_components/layouts/MainLayouts";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} bg-green-bg overflow-hidden antialiased`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
